### PR TITLE
Check softdevice update memfault sdk

### PR DESCRIPTION
**Pull request by SylvainHunaultOwlet**
Update the Memfault SDK of the branch check_softdevice

### CODE REVIEW

**Comment by SylvainHunaultOwlet** [comment]
Hi @chadg-owlet, @hiteshrai and @keith023,

BandFW uses the `check_softdevice` branch for Memfault and we are looking into updating the Memfault SDK.

Do any of you uses this branch too for your respective projects?

**Comment by hiteshrai** [comment]
> Hi @chadg-owlet, @hiteshrai and @keith023,
> 
> BandFW uses the `check_softdevice` branch for Memfault and we are looking into updating the Memfault SDK.
> 
> Do any of you uses this branch too for your respective projects?

No, we don’t. Thank you for checking.

**Comment by keith023** [comment]
> Hi @chadg-owlet, @hiteshrai and @keith023,
> 
> BandFW uses the `check_softdevice` branch for Memfault and we are looking into updating the Memfault SDK.
> 
> Do any of you uses this branch too for your respective projects?

Sock FW doesn't use this either

**Comment by SylvainHunaultOwlet** [comment]
Thank you for the update Keith and Hitesh.

**Comment by SylvainHunaultOwlet** [comment]
This branch is not used for Camera per offline discussion with Chad.

**Pull request merged**
